### ISSUE TITLE
testing APK

### ISSUE THREAD

**Issue by andrejguran** [Dannark/BWO#1]
Could you build testing APK to just test the app and feel of flutter for game? Thanks

**Comment by Dannark** [comment]
Sure, this is [version 1.0.1](https://drive.google.com/drive/folders/1lX372_MqHEnUDRCQkkTJY7llI3NmbIsh?usp=sharing)

But keep in mind that not all states are synchronized yet, I just added some build tools and i'm testing performance and other stuffs to see what works better. I will Probably remove it later for something else :)

Oh and you can't build house too close to the start area (0,0), you wont see the logs if you are not debugging it. I still have to do a custom Toast for that. hehe

If you have suggestions, feedback or any question feel free to ask

**Comment by Dannark** [comment]
Just Uploaded v1.0.3, i'm going to put the link in the main page.
