### ISSUE TITLE
AndroidManifest.xml could not be found

### ISSUE THREAD

**Issue by diybl** [Dannark/BWO#5]
AndroidManifest.xml could not be found.
Please check D:\pj\svn_game\BWO\android\AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android\AndroidManifest.xml?

**Comment by diybl** [comment]
flutter create .
has been sovled

**Comment by Dannark** [comment]
Yeah you have to create the project, thanks, I will add that to the instructions section readme page
